        <fieldset id='addUser'>
            <legend>Ajout d'un nouveau utilisateur</legend>
            <form enctype="multipart/form-data" class="user-form" method="POST" action="<?=htmlspecialchars($route)?>">
                <br>
                <label for="first_name">Prénom</label>
                <input type="text" name="first_name" value='<?= htmlspecialchars($newUser['first_name']) ?>'>
                <br><br>
                <label for="last_name">Nom</label>
                <input type="text" name="last_name" value='<?= htmlspecialchars($newUser['last_name']) ?>'>
                <br><br>
                <label for="mail">Mail</label>
                <input type="email" name="mail" value='<?= htmlspecialchars($newUser['mail']) ?>'>
                <br><br>
                <label for="password">Mot de passe</label>
                <input type="password" name="password" value='<?= htmlspecialchars($newUser['password']) ?>'>
                <br><br>
                <label for="is_admin">Administrateur</label>
                <input type="checkbox" name="is_admin" value="1" <?= $newUser['is_admin'] ? 'checked' : '' ?>>

                <br><br>
                
                <br><br>
                <button type="submit" name="submit" class='button'>Valider</button>
            </form>   
        </fieldset>
        
        <?php include_once('views/errors.phtml'); ?>