
<h1>Bienvenue dans votre admin Jardigénie</h1>

<div id="header2">
    <form action="index.php?route=byCat" method="POST">
        <div>
            <label for="cat-select" class="gras">Sélectionnez une catégorie:</label>

            <select name="cat" id="cat-select">
                <option value="">--choisissez votre catégorie--</option>
                <option value="Outils">Outils</option>
                <option value="Bacs">Bacs</option>
                <option value="Graines">Graines</option>
            </select>
            <input type="submit" class="button" value="OK" />
        </div>


    </form>
    <a href="index.php?route=addProduct" class="button">Ajouter un produit</a>

</div>

<section>


<?php foreach ($listProducts as $value):?> 

    

    <div class="products">
        <div class="flexleft">
        <img src="public/images/<?= htmlspecialchars($value['image']) ?>" alt="<?= htmlspecialchars($value['name']) ?>">
        <div class="content-product">
            <div>
                <div class="gras">
                <?= htmlspecialchars($value['name']) ?>
                </div>
                <div>
                    <span class="gras">Catégorie</span> : <?= htmlspecialchars($value['category']) ?>
                </div>
            </div>
            <div class="gras">
                Prix : <?= htmlspecialchars(number_format($value['price'], 2))?> €
            </div>
            <p><?= htmlspecialchars($value['description'])?></p>
        </div>
        </div>
        
        <div class="button-product">
            <a href="index.php?route=editProduct&id=<?= htmlspecialchars($value['product_id']) ?>" class="button">Modifier</a>
            <a href="index.php?route=deleteProduct&id=<?= htmlspecialchars($value['product_id']) ?>" class="button">Supprimer</a>
        </div>
    </div>
    <hr>
    
      
    <?php endforeach; ?> 

</section>
