<h1 class="text-center">Gestion des produits</h1>

<div id="header2">
    <form action="index.php?route=byCat" method="POST">
        <div>
            <label for="cat-select" class="gras">Sélectionnez une catégorie:</label>

            <select name="cat" id="cat-select">
                <option value="">--choisissez votre catégorie--</option>
                <option value="Outils">Outils</option>
                <option value="Bacs">Bacs</option>
                <option value="Graines">Graines</option>
            </select>
            <input type="submit" class="button" value="OK" />
        </div>


    </form>
    <a href="index.php?route=addProduct" class="btn btn-primary">Ajouter un produit</a>

</div>

<section>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Price</th>
      <th scope="col">Modifier</th>
      <th scope="col">Supprimer</th>

    </tr>
  </thead>
  <tbody>
    <?php foreach ($listProducts as $value):?> 
      <tr class="w-100">
        <th scope="row"><?= $value['product_id'] ?></th>
        <td><?= htmlspecialchars($value['name'])?></td>
        <td><?= htmlspecialchars($value['category'])?></td>
        <td><?= htmlspecialchars(number_format($value['price'], 2) .'€')?></td>
        
        <td><a href="index.php?route=editProduct&id=<?= htmlspecialchars($value['product_id']) ?>" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a></td>
        <td><a href="index.php?route=deleteProduct&id=<?= htmlspecialchars($value['product_id']) ?>" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a></td>
      </tr>
    <?php endforeach; ?> 
  </tbody>
</table>
</section>
