<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jardigénie</title>
    <link rel="stylesheet" href="public/css/style.css">
</head>
<body>

    <header>
        <a href="index.php?route=home">
            <img src="public/images/logojardigenie.png" alt="jardigenie">
        </a>
    </header>
    <main class="container">
        <?php include $template ?>
    </main>
    <footer></footer>
    
</body>
</html>