
<h1 class="text-center">Gestion des commandes</h1>

<section>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($listOrders as $value):?> 
      <tr class="w-100">
        <th scope="row"><?= $value['order_id'] ?></th>
        <td><?= htmlspecialchars($value['order_date'])?></td>
      </tr>
    <?php endforeach; ?> 
  </tbody>
</table>
</section>
