<h1 class="text-center mt-4 mb-4 fw-bold">Gestion des commandes</h1>

<table class="table table-bordered table-striped">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Nombre de produits</th>
      <th scope="col">Prix total</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($listOrders as $value):?> 
      <tr class="w-100">
        <th scope="row"><?= $value['order_id'] ?></th>
        <td><?= htmlspecialchars($value['order_date'])?></td>
        <td><?= htmlspecialchars($value['number_product'])?></td>
        <td><?= htmlspecialchars(number_format($value['total_price'], 2) . '€')?></td>
      </tr>
    <?php endforeach; ?> 
  </tbody>
</table>
