        
        
        <fieldset id='addProduct'>
            <legend>Ajout d'un nouveau produit</legend>
            <form enctype="multipart/form-data" class="user-form" method="POST" action="<?=htmlspecialchars($route)?>">
                <br>
                <label for="name">Nom du produit</label>
                <input type="text" name="name" value='<?= htmlspecialchars($newProduct['name']) ?>'>
                <br><br>
                <label for="price">Prix</label>
                <input type="number" name="price" step="0.01" min="0" max="100000" value='<?= htmlspecialchars($newProduct['price']) ?>'>
                <br><br>

                <label for="category">Catégorie</label>
                <select name="category">
                    <option value="<?= htmlspecialchars($newProduct['category']) ?>"><?= htmlspecialchars($newProduct['category']) ?></option>
                    <option value="Outils">Outils</option>
                    <option value="Bacs">Bacs</option>
                    <option value="Graines">Graines</option>
                </select>
                <br><br>
                <label for="description">Decription</label>
                <textarea name="description"><?= htmlspecialchars($newProduct['description']) ?></textarea>
                <br><br>

                <label for="image">Image</label>
                <input type="file" accept="image/*" name="img">
                <br><br>
                
                <br><br>
                <button type="submit" name="submit" class='button'>Valider</button>
            </form>   
        </fieldset>
        
        <?php include_once('views/errors.phtml'); ?>  


        
        

    

