
<h1>Bienvenue sur Jardigénie</h1>

<div id="header2">
    <form action="index.php?route=byCat" method="POST">
        <div>
            <label for="cat-select" class="gras">Sélectionnez une catégorie:</label>

            <select name="cat" id="cat-select">
                <option value="">--choisissez votre catégorie--</option>
                <option value="Outils">Outils</option>
                <option value="Bacs">Bacs</option>
                <option value="Graines">Graines</option>
            </select>
            <input type="submit" class="button" value="OK" />
        </div>


    </form>

</div>

<section>

<div class="container text-center">
  <div class="row gap-3">
    <?php foreach ($listProducts as $value):?> 
        <div class="card col-3">
            <img class="mx-auto d-block card-img-top rounded" style="height: 200px; width: 200px" src="public/images/<?= htmlspecialchars($value['image']) ?>" alt="<?= htmlspecialchars($value['name']) ?>">
            <div class="card-body">
                <h5 class="card-title"><?= htmlspecialchars($value['name']) ?></h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">Catégorie: <?= htmlspecialchars($value['category']) ?></h6>
                <p class="card-text"><p><?= htmlspecialchars($value['description'])?></p></p>

                <div class="gras">Prix : <?= htmlspecialchars(number_format($value['price'], 2))?> €</div>
                <!-- <a href="index.php?route=detailProduct&id=<?= htmlspecialchars($value['product_id']) ?>" class="button">Voir le détail</a> -->
                <a href="index.php?route=addCart&idProduct=<?= $value['product_id'] ?>&quantity=1" class="btn btn-success">Ajouter au panier</a>



            </div>
        </div>
    <?php endforeach; ?> 
  </div>
</div>

</section>
