<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="?route=home">
                <img src="/di_cube_4_jardigenie/public/images/logojardigenie" alt="JardiGenie Logo" height="40">
                Jardigénie Admin
            </a>
            <div class="d-flex">
                            <!-- <div class="collapse navbar-collapse" id="navbarNav"> -->
                <ul class="navbar-nav ms-auto">
                    <li class="navbar-text">
                        <a class="nav-link" href="/di_cube_4_jardigenie/front_office">Site marchand</a>
                    </li>
                    <li class="navbar-text">
                        <a class="nav-link" href="index.php">Tableau de bord</a>
                    </li>
                    <li class="navbar-text">
                        <a class="nav-link" href="?route=home">Produits</a>
                    </li>
                    <li class="navbar-text">
                        <a class="nav-link" href="?route=users">
                            <i class="bi bi-cart"></i> Utilisateurs
                        </a>
                    </li>
                    <li class="navbar-text">
                        <a class="nav-link" href="?route=orders">
                            <i class="bi bi-cart"></i> Commandes
                        </a>
                    </li>
                    <?php if (isset($_SESSION['user'])): ?>
                        <li class="navbar-text">
                            <a class="nav-link">
                                <?= $_SESSION['user']['first_name'] ?> <?= $_SESSION['user']['last_name'] ?>
                            </a>
                        </li>
                        <li class="navbar-text">
                            <a href="index.php?route=logout" class="btn btn-outline-light btn-sm nav-link">Déconnexion</a>
                        </li>
                    <?php else: ?>
                        <li class="navbar-text">
                            <a href="index.php?route=login" class="btn btn-outline-light btn-sm nav-link">Connexion</a>
                        </li>
                    <?php endif; ?> 
                </ul>
            </div>
        </div>
    </nav>
</header>
